### ISSUE TITLE
ebooks archive JSON Parser Error

### ISSUE THREAD

**Issue by errbufferoverfl** [mispy/twitter_ebooks#103]
When ever I run ebooks archive, after entering the auth details I get a JSON::Parser Error

```bash
/home/user/.rvm/gems/ruby-2.1.5/gems/json-1.8.3/lib/json/common.rb:155:in `initialize': A JSON text must at least contain two octets! (JSON::ParserError)
	from /home/user/.rvm/gems/ruby-2.1.5/gems/json-1.8.3/lib/json/common.rb:155:in `new'
	from /home/user/.rvm/gems/ruby-2.1.5/gems/json-1.8.3/lib/json/common.rb:155:in `parse'
	from /home/user/.rvm/gems/ruby-2.1.5/gems/twitter_ebooks-3.1.6/lib/twitter_ebooks/archive.rb:54:in `initialize'
	from /home/user/.rvm/gems/ruby-2.1.5/gems/twitter_ebooks-3.1.6/bin/ebooks:227:in `new'
	from /home/user/.rvm/gems/ruby-2.1.5/gems/twitter_ebooks-3.1.6/bin/ebooks:227:in `archive'
	from /home/user/.rvm/gems/ruby-2.1.5/gems/twitter_ebooks-3.1.6/bin/ebooks:411:in `command'
	from /home/user/.rvm/gems/ruby-2.1.5/gems/twitter_ebooks-3.1.6/bin/ebooks:429:in `<top (required)>'
	from /home/user/.rvm/gems/ruby-2.1.5/bin/ebooks:23:in `load'
	from /home/user/.rvm/gems/ruby-2.1.5/bin/ebooks:23:in `<main>'
	from /home/user/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
	from /home/user/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'
```
Not too sure where I could be going wrong?

**Comment by abhinavchh** [comment]
@errbufferoverfl Mind adding what fixed this? Facing the same issue

**Comment by errbufferoverfl** [comment]
@abhinavchh I removed all the files that the script generated after the first failed attempt, then re-ran it and it all worked, give that a shot!

**Comment by abhinavchh** [comment]
Got it, thanks!
