### ISSUE TITLE
"Invalid or expired token" when updating corpus

### ISSUE THREAD

**Issue by markbao** [mispy/twitter_ebooks#108]
Getting this issue when updating corpus. Tried `ebooks auth` to get a new token, but no dice.

```
> ebooks archive markbao corpus/markbao.json
Currently 3248 tweets for markbao
/home/mark/.rvm/gems/ruby-2.1.2/gems/twitter-5.16.0/lib/twitter/rest/response/raise_error.rb:15:in `on_complete': Invalid or expired token. (Twitter::Error::Unauthorized)
        from /home/mark/.rvm/gems/ruby-2.1.2/gems/faraday-0.9.1/lib/faraday/response.rb:9:in `block in call'
        from /home/mark/.rvm/gems/ruby-2.1.2/gems/faraday-0.9.1/lib/faraday/response.rb:57:in `on_complete'
        from /home/mark/.rvm/gems/ruby-2.1.2/gems/faraday-0.9.1/lib/faraday/response.rb:8:in `call'
        from /home/mark/.rvm/gems/ruby-2.1.2/gems/faraday-0.9.1/lib/faraday/request/url_encoded.rb:15:in `call'
        from /home/mark/.rvm/gems/ruby-2.1.2/gems/faraday-0.9.1/lib/faraday/request/multipart.rb:14:in `call'
        from /home/mark/.rvm/gems/ruby-2.1.2/gems/twitter-5.16.0/lib/twitter/rest/request/multipart_with_file.rb:19:in `call'
        from /home/mark/.rvm/gems/ruby-2.1.2/gems/faraday-0.9.1/lib/faraday/rack_builder.rb:139:in `build_response'
        from /home/mark/.rvm/gems/ruby-2.1.2/gems/faraday-0.9.1/lib/faraday/connection.rb:377:in `run_request'
        from /home/mark/.rvm/gems/ruby-2.1.2/gems/faraday-0.9.1/lib/faraday/connection.rb:140:in `get'
        from /home/mark/.rvm/gems/ruby-2.1.2/gems/twitter-5.16.0/lib/twitter/rest/request.rb:33:in `perform'
        from /home/mark/.rvm/gems/ruby-2.1.2/gems/twitter-5.16.0/lib/twitter/rest/utils.rb:50:in `perform_request'
        from /home/mark/.rvm/gems/ruby-2.1.2/gems/twitter-5.16.0/lib/twitter/rest/utils.rb:95:in `perform_request_with_objects'
        from /home/mark/.rvm/gems/ruby-2.1.2/gems/twitter-5.16.0/lib/twitter/rest/utils.rb:139:in `objects_from_response_with_user'
        from /home/mark/.rvm/gems/ruby-2.1.2/gems/twitter-5.16.0/lib/twitter/rest/timelines.rb:49:in `user_timeline'
        from /home/mark/.rvm/gems/ruby-2.1.2/gems/twitter_ebooks-3.1.6/lib/twitter_ebooks/archive.rb:93:in `block in sync_to'
        from /home/mark/.rvm/gems/ruby-2.1.2/gems/twitter_ebooks-3.1.6/lib/twitter_ebooks/archive.rb:90:in `loop'
        from /home/mark/.rvm/gems/ruby-2.1.2/gems/twitter_ebooks-3.1.6/lib/twitter_ebooks/archive.rb:90:in `sync_to'
        from /home/mark/.rvm/gems/ruby-2.1.2/gems/twitter_ebooks-3.1.6/lib/twitter_ebooks/archive.rb:68:in `block in sync'
        from /home/mark/.rvm/gems/ruby-2.1.2/gems/twitter_ebooks-3.1.6/lib/twitter_ebooks/archive.rb:66:in `open'
        from /home/mark/.rvm/gems/ruby-2.1.2/gems/twitter_ebooks-3.1.6/lib/twitter_ebooks/archive.rb:66:in `sync'
        from /home/mark/.rvm/gems/ruby-2.1.2/gems/twitter_ebooks-3.1.6/bin/ebooks:227:in `archive'
        from /home/mark/.rvm/gems/ruby-2.1.2/gems/twitter_ebooks-3.1.6/bin/ebooks:411:in `command'
        from /home/mark/.rvm/gems/ruby-2.1.2/gems/twitter_ebooks-3.1.6/bin/ebooks:429:in `<top (required)>'
        from /home/mark/.rvm/gems/ruby-2.1.2/bin/ebooks:23:in `load'
        from /home/mark/.rvm/gems/ruby-2.1.2/bin/ebooks:23:in `<main>'
        from /home/mark/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'
        from /home/mark/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by patr1ck** [comment]
@markbao see #113 for a fix
