### ISSUE TITLE
Can't get example to run

### ISSUE THREAD

**Issue by NKromelow** [mispy/twitter_ebooks#117]
Hi, I'm trying to use the example to get a bot running, but I'm getting this error and i'm not sure how tot fix it: 
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/twitter-5.16.0/lib/twitter/rest/request.rb:37:in `rescue in perform': SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (Twitter::Error)
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/twitter-5.16.0/lib/twitter/rest/request.rb:32:in `perform'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/twitter-5.16.0/lib/twitter/rest/utils.rb:50:in `perform_request'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/twitter-5.16.0/lib/twitter/rest/utils.rb:72:in `perform_request_with_object'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/twitter-5.16.0/lib/twitter/rest/utils.rb:57:in `perform_get_with_object'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/twitter-5.16.0/lib/twitter/rest/users.rb:51:in `verify_credentials'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/twitter-5.16.0/lib/twitter/rest/users.rb:258:in `user'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/twitter_ebooks-3.1.6/lib/twitter_ebooks/bot.rb:322:in `update_myself'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/twitter_ebooks-3.1.6/lib/twitter_ebooks/bot.rb:351:in `prepare'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/twitter_ebooks-3.1.6/bin/ebooks:337:in `block (2 levels) in start'

Any suggestions? Thanks!

**Comment by Ordinaryperson2** [comment]
I'm having the same issue, both when starting the bot and when trying to create an archive (i don't already have one).
I've checked my keys so many times, and even regenerated them, but no luck. Also tried putting an intentionally wrong secret in, but no difference. Any ideas?
(If it's simple please be kind, I've never used Ruby before)

Archive:
```
C:/Ruby23/lib/ruby/gems/2.3.0/gems/twitter-5.16.0/lib/twitter/rest/request.rb:37
:in `rescue in perform': SSL_connect returned=1 errno=0 state=SSLv3 read server
certificate B: certificate verify failed (Twitter::Error)
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/twitter-5.16.0/lib/twitter/rest/
request.rb:32:in `perform'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/twitter-5.16.0/lib/twitter/rest/
utils.rb:50:in `perform_request'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/twitter-5.16.0/lib/twitter/rest/
utils.rb:95:in `perform_request_with_objects'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/twitter-5.16.0/lib/twitter/rest/
utils.rb:139:in `objects_from_response_with_user'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/twitter-5.16.0/lib/twitter/rest/
timelines.rb:49:in `user_timeline'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/twitter_ebooks-3.1.6/lib/twitter
_ebooks/archive.rb:93:in `block in sync_to'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/twitter_ebooks-3.1.6/lib/twitter
_ebooks/archive.rb:90:in `loop'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/twitter_ebooks-3.1.6/lib/twitter
_ebooks/archive.rb:90:in `sync_to'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/twitter_ebooks-3.1.6/lib/twitter
_ebooks/archive.rb:68:in `block in sync'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/twitter_ebooks-3.1.6/lib/twitter
_ebooks/archive.rb:66:in `open'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/twitter_ebooks-3.1.6/lib/twitter
_ebooks/archive.rb:66:in `sync'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/twitter_ebooks-3.1.6/bin/ebooks:
227:in `archive'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/twitter_ebooks-3.1.6/bin/ebooks:
411:in `command'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/twitter_ebooks-3.1.6/bin/ebooks:
429:in `<top (required)>'
        from C:/Ruby23/bin/ebooks:23:in `load'
        from C:/Ruby23/bin/ebooks:23:in `<main>'
```
Start:
```
C:/Ruby23/lib/ruby/gems/2.3.0/gems/twitter-5.16.0/lib/twitter/rest/request.rb:37
:in `rescue in perform': SSL_connect returned=1 errno=0 state=SSLv3 read server
certificate B: certificate verify failed (Twitter::Error)
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/twitter-5.16.0/lib/twitter/rest/
request.rb:32:in `perform'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/twitter-5.16.0/lib/twitter/rest/
utils.rb:50:in `perform_request'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/twitter-5.16.0/lib/twitter/rest/
utils.rb:72:in `perform_request_with_object'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/twitter-5.16.0/lib/twitter/rest/
utils.rb:57:in `perform_get_with_object'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/twitter-5.16.0/lib/twitter/rest/
users.rb:51:in `verify_credentials'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/twitter-5.16.0/lib/twitter/rest/
users.rb:258:in `user'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/twitter_ebooks-3.1.6/lib/twitter
_ebooks/bot.rb:322:in `update_myself'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/twitter_ebooks-3.1.6/lib/twitter
_ebooks/bot.rb:351:in `prepare'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/twitter_ebooks-3.1.6/bin/ebooks:
337:in `block (2 levels) in start'
```

**Comment by eldritchreality** [comment]
Have you got a working ntp daemon on your machine?  
  
I used to have all sorts of twitter authentication issues via the ebooks gem until I realised that my machine's clock was 30 minutes out from the twitters clock, and that meant that the API was rejecting me.
