### ISSUE TITLE
Error Starting Bot

### ISSUE THREAD

**Issue by MrActivisionary** [mispy/twitter_ebooks#120]
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/twitter_ebooks-3.1.6/bin/ebooks:392:in `load': cannot load such file -- bots.rb (LoadError)
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/twitter_ebooks-3.1.6/bin/ebooks:392:in `load_bots'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/twitter_ebooks-3.1.6/bin/ebooks:301:in `console'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/twitter_ebooks-3.1.6/bin/ebooks:416:in `command'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/twitter_ebooks-3.1.6/bin/ebooks:429:in `<top (required)>'
        from C:/Ruby23-x64/bin/ebooks:23:in `load'
        from C:/Ruby23-x64/bin/ebooks:23:in `<main>'

Also when trying to start from ebooks folder:
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/twitter-5.16.0/lib/twitter/rest/request.rb:37:in `rescue in perform': SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (Twitter::Error)
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/twitter-5.16.0/lib/twitter/rest/request.rb:32:in `perform'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/twitter-5.16.0/lib/twitter/rest/utils.rb:50:in `perform_request'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/twitter-5.16.0/lib/twitter/rest/utils.rb:72:in `perform_request_with_object'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/twitter-5.16.0/lib/twitter/rest/utils.rb:57:in `perform_get_with_object'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/twitter-5.16.0/lib/twitter/rest/users.rb:51:in `verify_credentials'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/twitter-5.16.0/lib/twitter/rest/users.rb:258:in `user'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/twitter_ebooks-3.1.6/lib/twitter_ebooks/bot.rb:322:in `update_myself'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/twitter_ebooks-3.1.6/lib/twitter_ebooks/bot.rb:351:in `prepare'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/twitter_ebooks-3.1.6/bin/ebooks:337:in `block (2 levels) in start'

**Comment by negatendo** [comment]
For that first error, you definitely want to run the ebooks command from within a bot directory. As for the second, take a look at this previous ticket: https://github.com/mispy/twitter_ebooks/issues/39
