### ISSUE TITLE
JSON exception when archiving

### ISSUE THREAD

**Issue by Chenny2** [mispy/twitter_ebooks#124]
Sometimes I get errors like that when archiving.

```
C:/Ruby22/lib/ruby/gems/2.2.0/gems/json-1.8.3/lib/json/common.rb:155:in `initialize': A JSON text must at least contain two octets! (JSON::ParserError)
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/json-1.8.3/lib/json/common.rb:155:in `new'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/json-1.8.3/lib/json/common.rb:155:in `parse'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/twitter_ebooks-3.1.6/lib/twitter_ebooks/archive.rb:54:in `initialize'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/twitter_ebooks-3.1.6/bin/ebooks:227:in `new'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/twitter_ebooks-3.1.6/bin/ebooks:227:in `archive'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/twitter_ebooks-3.1.6/bin/ebooks:411:in `command'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/twitter_ebooks-3.1.6/bin/ebooks:429:in `<top (required)>'
        from C:/Ruby22/bin/ebooks:23:in `load'
        from C:/Ruby22/bin/ebooks:23:in `<main>'
```

**Comment by atlgeek007** [comment]
Same issue here :-(

**Comment by btamayo** [comment]
Seems like it may happen when your archive file exists but is empty (technically also if malformed):

`archive.rb`'s `initialize`: line ~50
```
@filetext = File.read(@path, :encoding => 'utf-8')
@tweets = JSON.parse(@filetext, symbolize_names: true)
log "Currently #{@tweets.length} tweets for #{@username}"
```

A quick fix would be to just put that in an `if` that checks that `@filetext` has `length > 0`:


```
@filetext = File.read(@path, :encoding => 'utf-8')
if @filetext && @filetext.length > 0
    @tweets = JSON.parse(@filetext, symbolize_names: true)
    log "Currently #{@tweets.length} tweets for #{@username}"
end
```
