### ISSUE TITLE
Heroku-specific error

### ISSUE THREAD

**Issue by fontiago** [mispy/twitter_ebooks#129]
Everything _appears_ to be set up to the point of having the repo on Heroku, but when I run `bundle exec ebooks start` on Heroku (through Heroku CLI, `heroku run bash`), I get the following output:

```
~ $ bundle exec ebooks start
@fontiagoebooks: User information updated
/app/lib/twitter_ebooks/model.rb:49:in `load': dump format error(0x2) (ArgumentError)
	from /app/lib/twitter_ebooks/model.rb:49:in `block in load'
	from /app/lib/twitter_ebooks/model.rb:48:in `instance_eval'
	from /app/lib/twitter_ebooks/model.rb:48:in `load'
	from bots.rb:22:in `on_startup'
	from /app/lib/twitter_ebooks/bot.rb:371:in `fire'
	from /app/lib/twitter_ebooks/bot.rb:353:in `prepare'
	from /app/bin/ebooks:361:in `block (2 levels) in start
```

And when I run simply `ebooks start` on Heroku:

```
~ $ ebooks start
/app/vendor/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- twitter_ebooks (LoadError)
	from /app/vendor/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /app/bin/ebooks:4:in `<main>'
```

Both of these commands work locally on my machine (OS X El Capitan). I'm guessing I've mucked something up with git, as evidenced by the fact that I _can_ run `bundle exec ebooks archive <username> corpus/<username>.json`:

```
fatal: Not a git repository (or any parent up to mount point /app)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
Currently 3253 tweets for <username>
No new tweets
```

and that works the same as my local machine aside from the git repository error. Any help?

**Comment by fontiago** [comment]
Should be noted that it... obviously is a git repo, and when I run `git init` on Heroku it simply removes the git repository errors without fixing anything else.
