### ISSUE TITLE
Twitter:Error:Unauthorized

### ISSUE THREAD

**Issue by smiba** [mispy/twitter_ebooks#143]
The bot always worked, until I updated it today. Not sure what caused it but somewhere in the period of now and 6 months (last time of restart) something changed preventing it from logging in. Before the restart it went just fine so the keys did not expire

Any idea?

```
@bot: User information updated
@bot: Loading model model/tweets.model
@bot: starting tweet stream
@bot: Twitter::Error::Unauthorized
        /usr/local/rvm/gems/ruby-2.3.3/gems/twitter-5.17.0/lib/twitter/streaming/response.rb:21:in `on_headers_complete'
        /usr/local/rvm/gems/ruby-2.3.3/gems/twitter-5.17.0/lib/twitter/streaming/response.rb:16:in `<<'
        /usr/local/rvm/gems/ruby-2.3.3/gems/twitter-5.17.0/lib/twitter/streaming/response.rb:16:in `<<'
        /usr/local/rvm/gems/ruby-2.3.3/gems/twitter-5.17.0/lib/twitter/streaming/connection.rb:22:in `stream'
        /usr/local/rvm/gems/ruby-2.3.3/gems/twitter-5.17.0/lib/twitter/streaming/client.rb:119:in `request'
        /usr/local/rvm/gems/ruby-2.3.3/gems/twitter-5.17.0/lib/twitter/streaming/client.rb:92:in `user'
        /usr/local/rvm/gems/ruby-2.3.3/gems/twitter_ebooks-3.1.6/lib/twitter_ebooks/bot.rb:362:in `start'
        /usr/local/rvm/gems/ruby-2.3.3/gems/twitter_ebooks-3.1.6/bin/ebooks:346:in `block (3 levels) in start'
        /usr/local/rvm/gems/ruby-2.3.3/gems/twitter_ebooks-3.1.6/bin/ebooks:344:in `loop'
        /usr/local/rvm/gems/ruby-2.3.3/gems/twitter_ebooks-3.1.6/bin/ebooks:344:in `block (2 levels) in start'
@bot: Sleeping before reconnect
```

**Comment by rafitamolin** [comment]
I'm getting this same error. Did you manage to fix it?
