### ISSUE TITLE
Twitter::Error::Unauthorized

### ISSUE THREAD

**Issue by rafitamolin** [mispy/twitter_ebooks#154]
Everything in my config files is correct, including tokens. I've tried everything and I don't know how to make it work.

```@rafitaml_ebooks: User information updated
@rafitaml_ebooks: Loading model model/rafitamolin.model
@rafitaml_ebooks: starting tweet stream
@rafitaml_ebooks: Twitter::Error::Unauthorized
        /var/lib/gems/2.4.0/gems/twitter-5.17.0/lib/twitter/streaming/response.rb:21:in `on_headers_complete'
        /var/lib/gems/2.4.0/gems/twitter-5.17.0/lib/twitter/streaming/response.rb:16:in `<<'
        /var/lib/gems/2.4.0/gems/twitter-5.17.0/lib/twitter/streaming/response.rb:16:in `<<'
        /var/lib/gems/2.4.0/gems/twitter-5.17.0/lib/twitter/streaming/connection.rb:22:in `stream'
        /var/lib/gems/2.4.0/gems/twitter-5.17.0/lib/twitter/streaming/client.rb:119:in `request'
        /var/lib/gems/2.4.0/gems/twitter-5.17.0/lib/twitter/streaming/client.rb:92:in `user'
        /var/lib/gems/2.4.0/gems/twitter_ebooks-3.1.6/lib/twitter_ebooks/bot.rb:362:in `start'
        /var/lib/gems/2.4.0/gems/twitter_ebooks-3.1.6/bin/ebooks:346:in `block (3 levels) in start'
        /var/lib/gems/2.4.0/gems/twitter_ebooks-3.1.6/bin/ebooks:344:in `loop'
        /var/lib/gems/2.4.0/gems/twitter_ebooks-3.1.6/bin/ebooks:344:in `block (2 levels) in start'
@rafitaml_ebooks: Sleeping before reconnect```

**Comment by rafitamolin** [comment]
My VPS was running 13 minutes behind the actual real date, which caused the problem. Asking my VPS manager to fix it fixed this problem.
