### ISSUE TITLE
2.3.2 not compatiable with 2.2.* models? undefined method `[]' for #<Ebooks::Model:0x000000015c5908>

### ISSUE THREAD

**Issue by zhuowei** [mispy/twitter_ebooks#72]
When I attempt to run ebooks gen model/mymodel.model, I get:
```
Faraday::Builder is now Faraday::RackBuilder.
/var/lib/gems/1.9.1/gems/twitter_ebooks-2.3.2/lib/twitter_ebooks/model.rb:21:in `block in load': undefined method `[]' for #<Ebooks::Model:0x000000015c5908> (NoMethodError)
	from /var/lib/gems/1.9.1/gems/twitter_ebooks-2.3.2/lib/twitter_ebooks/model.rb:19:in `instance_eval'
	from /var/lib/gems/1.9.1/gems/twitter_ebooks-2.3.2/lib/twitter_ebooks/model.rb:19:in `load'
	from /var/lib/gems/1.9.1/gems/twitter_ebooks-2.3.2/bin/ebooks:77:in `gen'
	from /var/lib/gems/1.9.1/gems/twitter_ebooks-2.3.2/bin/ebooks:205:in `command'
	from /var/lib/gems/1.9.1/gems/twitter_ebooks-2.3.2/bin/ebooks:217:in `<top (required)>'
	from /usr/local/bin/ebooks:23:in `load'
	from /usr/local/bin/ebooks:23:in `<main>'
```
I'm using Twitter_ebooks 2.3.2 on Ubuntu 14.04 with Ruby 1.9.1. This model was generated on one of the 2.2.* versions; using this with a 2.3.2-generated model worked fine.

**Comment by mispy** [comment]
Since version 3 models are explicitly not backwards compatible I guess I can close this >_>
