### ISSUE TITLE
Exception on mention

### ISSUE THREAD

**Issue by elad661** [mispy/twitter_ebooks#74]
I got this stacktrace when someone mentioned my bot
````
#<NoMethodError: undefined method `each_with_index' for nil:NilClass>
        /home/elad/.gem/ruby/gems/twitter_ebooks-3.0.6/lib/twitter_ebooks/suffix.rb:59:in `block in generate'
        /home/elad/.gem/ruby/gems/twitter_ebooks-3.0.6/lib/twitter_ebooks/suffix.rb:56:in `upto'
        /home/elad/.gem/ruby/gems/twitter_ebooks-3.0.6/lib/twitter_ebooks/suffix.rb:56:in `generate'
        /home/elad/.gem/ruby/gems/twitter_ebooks-3.0.6/lib/twitter_ebooks/model.rb:220:in `make_statement'
        /home/elad/.gem/ruby/gems/twitter_ebooks-3.0.6/lib/twitter_ebooks/model.rb:288:in `make_response'
        bots.rb:63:in `block in on_mention'
        /home/elad/.gem/ruby/gems/twitter_ebooks-3.0.6/lib/twitter_ebooks/bot.rb:353:in `call'
        /home/elad/.gem/ruby/gems/twitter_ebooks-3.0.6/lib/twitter_ebooks/bot.rb:353:in `delay'
        bots.rb:61:in `on_mention'
        /home/elad/.gem/ruby/gems/twitter_ebooks-3.0.6/lib/twitter_ebooks/bot.rb:344:in `fire'
        /home/elad/.gem/ruby/gems/twitter_ebooks-3.0.6/lib/twitter_ebooks/bot.rb:287:in `receive_event'
        /home/elad/.gem/ruby/gems/twitter_ebooks-3.0.6/lib/twitter_ebooks/bot.rb:334:in `block in start'
        /home/elad/.gem/ruby/gems/twitter-5.13.0/lib/twitter/streaming/client.rb:115:in `block in request'
        /home/elad/.gem/ruby/gems/twitter-5.13.0/lib/twitter/streaming/response.rb:27:in `call'
        /home/elad/.gem/ruby/gems/twitter-5.13.0/lib/twitter/streaming/response.rb:27:in `block in on_body'
        /home/elad/.gem/ruby/gems/twitter-5.13.0/lib/twitter/streaming/response.rb:25:in `each'
        /home/elad/.gem/ruby/gems/twitter-5.13.0/lib/twitter/streaming/response.rb:25:in `on_body'
        /home/elad/.gem/ruby/gems/twitter-5.13.0/lib/twitter/streaming/response.rb:16:in `<<'
        /home/elad/.gem/ruby/gems/twitter-5.13.0/lib/twitter/streaming/response.rb:16:in `<<'
        /home/elad/.gem/ruby/gems/twitter-5.13.0/lib/twitter/streaming/connection.rb:22:in `stream'
        /home/elad/.gem/ruby/gems/twitter-5.13.0/lib/twitter/streaming/client.rb:118:in `request'
        /home/elad/.gem/ruby/gems/twitter-5.13.0/lib/twitter/streaming/client.rb:91:in `user'
        /home/elad/.gem/ruby/gems/twitter_ebooks-3.0.6/lib/twitter_ebooks/bot.rb:333:in `start'
        /home/elad/.gem/ruby/gems/twitter_ebooks-3.0.6/bin/ebooks:261:in `block (3 levels) in start'
        /home/elad/.gem/ruby/gems/twitter_ebooks-3.0.6/bin/ebooks:259:in `loop'
        /home/elad/.gem/ruby/gems/twitter_ebooks-3.0.6/bin/ebooks:259:in `block (2 levels) in start'
````

**Comment by mispy** [comment]
Looks like there's a nil sentence in the model, interesting. If you're still running into this can you send me the corpus involved?
