### ISSUE TITLE
ERROR:  Error installing twitter_ebooks:

### ISSUE THREAD

**Issue by PiotrMi** [mispy/twitter_ebooks#95]
ERROR:  Error installing twitter_ebooks:
        ERROR: Failed to build gem native extension.

        /usr/bin/ruby1.9.1 extconf.rb
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- mkmf (LoadError)
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from extconf.rb:1:in `<main>'

Gem files will remain installed in /var/lib/gems/1.9.1/gems/http_parser.rb-0.6.0 for inspection.
Results logged to /var/lib/gems/1.9.1/gems/http_parser.rb-0.6.0/ext/ruby_http_parser/gem_make.out

**Comment by negatendo** [comment]
twitter_ebooks requires ruby 2.0+. Looks like you're running ruby 1.9.1.

**Comment by polymetric1** [comment]
I'm running `ruby 2.2.3p173` on cygwin and I get almost the same error. https://gist.github.com/polymetric1/f269f415240ef4744b98 I really have no idea what's going on here, if someone could help that'd be nice

**Comment by polymetric1** [comment]
I've fixed the above error. It was caused because I didn't have a required library installed (libgmp and libcrypto)
But now there is a build error:
```
$ gem install twitter_ebooks
ERROR:  While executing gem ... (TypeError)
    no implicit conversion of nil into String
```
